till: convert argument to option
argument was optional before
fix usage string

diff --git a/till b/till
--- a/till
+++ b/till
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 helpmessage() {
-   echo -e "usage: ./till.sh [skip]\n"
+   echo -e "usage: till\n"
    echo -e "   -a, --all      use all files found"
    echo -e "   -c, --config   cmsrun config"
    echo -e "   -e, --echo     print run numbers"
@@ -11,8 +11,9 @@ helpmessage() {
    echo -e "   -l, --logs     logs directory"
    echo -e "   -n             number of files"
    echo -e "   -o, --output   output directory"
+   echo -e "   -r, --runs     runs to omit"
    echo -e "   -s, --stream   data streamer"
-   echo -e "   -u, --update   update [skip] with runs"
+   echo -e "   -u, --update   update [runs] with runs"
 }
 
 ARGS=()
@@ -33,6 +34,8 @@ while [ $# -gt 0 ]; do
       -n=*)          n="${1#*=}"; shift ;;
       -o|--output)   out="$2"; shift 2 ;;
       --output=*)    out="${1#*=}"; shift ;;
+      -r|--runs)     runs="$2"; shift 2 ;;
+      --runs=*)      runs="${1#*=}"; shift ;;
       -s|--stream)   stream="$2"; shift 2 ;;
       --stream=*)    stream="${1#*=}"; shift ;;
       -u|--update)   update=1; shift ;;
@@ -43,18 +46,16 @@ done
 
 set -- "${ARGS[@]}"
 
-[ $# -gt 1 ] && { echo -e "check arguments\n"; exit 1; }
+[ $# -ne 0 ] && { echo -e "check arguments\n"; exit 1; }
 
 [ $grow -a ! $config ] && {
    echo -e "  \033[31mno tree (config) to grow\033[0m\n"; exit 1; }
 [ ! $grow -a $update ] && {
    echo -e "  \033[31mcannot update without growing\033[0m\n"; exit 1; }
 
-skip=$1
-
-[ ! -f $skip ] && {
-   echo -e "  \033[31mfile not found: $skip\033[0m\n"; exit 1; }
-[ ! $skip -a $update ] && {
+[ ! -f $runs ] && {
+   echo -e "  \033[31mfile not found: $runs\033[0m\n"; exit 1; }
+[ ! $runs -a $update ] && {
    echo -e "  \033[31mno file to update\033[0m\n"; exit 1; }
 
 [ $out ] &&
@@ -76,7 +77,7 @@ for high in $(ls $data); do
    for low in $(ls $data/$high); do
       run=$high$low
 
-      [ $skip ] && grep -Fqx "$run" $skip ||
+      [ $runs ] && grep -Fqx "$run" $runs ||
          runs+=("$run")
    done
 done
@@ -103,6 +104,6 @@ for run in ${runs[@]}; do
    else
       echo -e "  prepared: \033[34m$list\033[0m"
       grow $fwargs -l $logdir/$run/ -o $outdir/$run/ $list $config
-      [ $update -a $skip ] && echo $run >> $skip
+      [ $update -a $runs ] && echo $run >> $runs
    fi
 done
